###
GET https://{{url}}/orders?search=202003-1033
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET https://{{url}}/orders?status=2
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET https://{{url}}/orders/1?expand=orderlines
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET https://{{url}}/orders?start_date=2020-03-12&period = day&duration = 2
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST https://{{url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "test order33",
  "client_id": 1
}

###
PUT https://{{url}}/orders/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "fzef order33",
  "client_id": 1
}

###
PUT https://{{url}}/orders/1/abandon
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT https://{{url}}/orders/2/confirm
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT https://{{url}}/orders/2/done
Content-Type: application/json
Authorization: Bearer {{token}}

###