###
PUT https://{{url}}/vehicles/increase-stock/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 30
}

###
PUT https://{{url}}/vehicles/minus-stock/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 40
}

### create
POST https://{{url}}/vehicles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "model_id": 50,
  "energy_id": 1,
  "year": 2008,
  "description": "Nice car",
  "stock": 10
}

###
GET https://{{url}}/vehicles/3
Content-Type: application/json
Authorization: Bearer {{token}}

### search by make id and energy id
GET https://{{url}}/vehicles?make_id=1&energy_id=1
Content-Type: application/json
Authorization: Bearer {{token}}

### general search
GET https://{{url}}/vehicles?search=jeep
Content-Type: application/json
Authorization: Bearer {{token}}

###