###
PUT https://{{url}}/vehicles/2/increase-stock
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 30
}

###
PUT https://{{url}}/vehicles/2/minus-stock
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 5
}

### create
POST https://{{url}}/vehicles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "model_id": 50,
  "energy_id": 1,
  "year": 2008,
  "description": "Nice car",
  "stock": 10
}

###
GET https://{{url}}/vehicles/3
Content-Type: application/json
Authorization: Bearer {{token}}

### search by make id and energy id
GET https://{{url}}/vehicles?make_id=1&energy_id=1
Content-Type: application/json
Authorization: Bearer {{token}}

### general search
GET https://{{url}}/vehicles?search=jeep
Content-Type: application/json
Authorization: Bearer {{token}}

### upload grey card
POST https://{{url}}/vehicles/upload/2
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="greyCard"; filename="greycard.png"

< ./greycard.png
--WebAppBoundary--

###